version: '3.7'

services:
  hydra:
    image: oryd/hydra:v1.9.2
    ports:
    - 4444:4444
    - 4445:4445
    - 5555:5555
    command:
      serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    volumes:
      -
        type: bind
        source: ./hydra-config/dev
        target: /etc/config/hydra
    env_file:
      .env
    depends_on:
      - hydra-migrate
    restart: always
  
  hydra-migrate:
    image: oryd/hydra:v1.9.2
    command:
      migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      -
        type: bind
        source: ./hydra-config/dev
        target: /etc/config/hydra
    env_file:
      .env
    restart: on-failure

  dev-db:
    platform: linux/amd64
    image: mdillon/postgis:9.6-alpine
    restart: 'always'
    ports:
        - 5433:5432
    environment:
        - ALLOW_IP_RANGE=0.0.0.0/0
        - POSTGRES_DB=osm-teams
        - PGDATA=/opt/postgres/data
    volumes:
        - ./docker-data/dev-db:/opt/postgres/data

  test-db:
    platform: linux/amd64
    image: mdillon/postgis:9.6-alpine
    restart: 'always'
    ports:
        - 5434:5432
    environment:
        - ALLOW_IP_RANGE=0.0.0.0/0
        - POSTGRES_DB=osm-teams-test
        - PGDATA=/opt/postgres/data
    volumes:
        - ./docker-data/test-db:/opt/postgres/data    