swagger: '2.0'
info:
  description: A teams API for OpenStreetMap
  version: '0.0.0'
  title: OSM Teams
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: teams
    description: Teams
paths:
  /api/teams:
    get:
      summary: list of teams
      tags:
        - teams
      responses:
        200:
          description: Team object
